// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZbH5cINF4dmtKlCbRUzOxrTrKQ-3NrM4',
    appId: '1:286699711215:web:b149525c6836b77dea891a',
    messagingSenderId: '286699711215',
    projectId: 'rasseni-8004a',
    authDomain: 'rasseni-8004a.firebaseapp.com',
    storageBucket: 'rasseni-8004a.firebasestorage.app',
    measurementId: 'G-XPSLQMGK3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHOsTqAxdj4tD8D6-jhJoyT_11Vpkr4g',
    appId: '1:286699711215:android:68beaf76f123596eea891a',
    messagingSenderId: '286699711215',
    projectId: 'rasseni-8004a',
    storageBucket: 'rasseni-8004a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmj25ha7zHLtaYOT048rxSNAUWcFqkCvc',
    appId: '1:286699711215:ios:a3b52796346c72f6ea891a',
    messagingSenderId: '286699711215',
    projectId: 'rasseni-8004a',
    storageBucket: 'rasseni-8004a.firebasestorage.app',
    iosBundleId: 'com.example.raseeni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmj25ha7zHLtaYOT048rxSNAUWcFqkCvc',
    appId: '1:286699711215:ios:a3b52796346c72f6ea891a',
    messagingSenderId: '286699711215',
    projectId: 'rasseni-8004a',
    storageBucket: 'rasseni-8004a.firebasestorage.app',
    iosBundleId: 'com.example.raseeni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZbH5cINF4dmtKlCbRUzOxrTrKQ-3NrM4',
    appId: '1:286699711215:web:e47c135b692b069fea891a',
    messagingSenderId: '286699711215',
    projectId: 'rasseni-8004a',
    authDomain: 'rasseni-8004a.firebaseapp.com',
    storageBucket: 'rasseni-8004a.firebasestorage.app',
    measurementId: 'G-YM4CBNFTEB',
  );
}
